### ISSUE TITLE
Type 'string' is not assignable to type 'TleLine1'.

### ISSUE THREAD

**Issue by 1valdis** [thkruz/ootk#28]
Hi, first of all, thank you for the lib, keep up the good work! I'm currently looking if I can replace `satellite.js` with your `ootk` for my project, because some satellites appear in bugged positions while using `satellite.js`🙈 Also if some help is needed with the library, I'd be glad to assist😊

**Describe the bug**
I'm trying to create a satellite as the README shows:
```ts
const tle1 = 'string with tle1'
const tle2 = 'string with tle2'
const satellite = new Satellite({ tle1, tle2 })
```

But I get
```
Type 'string' is not assignable to type 'TleLine1'.
  Type 'string' is not assignable to type '{ __TYPE__: "TLE Line 1"; }'.
```

From the README I assumed those are just strings, but apparently they need to be created in some sort of custom way?

**Expected behavior**
Passing `tle1` and `tle2` as strings just works.

**Comment by thkruz** [comment]
My apologizes. I just fell behind updating the documentation. I have just merged an updated version with a better example.

You need to actually provide a two line element set (TLE) such as:

```ts
const tle1 = "1 25544U 98067A   24235.16000531  .00028314  00000-0  49252-3 0 99995" as TleLine1;
const tle2 = "2 25544  51.6402 348.4828 0004893 236.4095 123.6428 15.50549723468780" as TleLine2;
```
This is a heavily typed library. I have spent years debugging things only to find it is a degrees vs radians mistake or meters vs kilometers. To help combat that I am overly rigid on making you specify that you have the right units.

I should point out, that for more general purposes you might want to consider https://github.com/thkruz/ootk-core/. This library is built on top of the core with more technical features and special use cases for https://keeptrack.space. It might be overkill if you don't need the extra features.

**Comment by 1valdis** [comment]
It's not the first time that I'm getting called out for ChatGPT use despite I've made everything related to actual satellites without its help😅; it was only useful in the beginning and didn't do any of the juicy stuff. So I've removed that section from the readme; I don't use it anymore anyway.
